#spring:
#  data:
#    jpa:
#      repositories:
#        enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/driver
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
#server:
#  port: 8080
#
